spring:
  application:
    name: hub-service

  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

#유레카 등록
eureka:
  instance:
    # 도커 컨테이너 접근을 위한 설정
    prefer-ip-address: false
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3150/eureka/